# -*- coding: utf-8 -*-
"""quick_sort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18XDy7q8-WvpUuH74B5890TQUVDPfyTj4
"""

def quick_sort(arr):
    if len(arr) <= 1:
        return arr  # Base case: already sorted
    else:
        pivot = arr[0]  # Choose the first element as pivot
        left = [x for x in arr[1:] if x <= pivot]  # Elements less than or equal to pivot
        right = [x for x in arr[1:] if x > pivot]   # Elements greater than pivot
        return quick_sort(left) + [pivot] + quick_sort(right)  # Recursive sort and combine

# Example usage:
arr = [10, 7, 8, 9, 1, 5]
sorted_arr = quick_sort(arr)
print("Sorted array:", sorted_arr)